/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Eranda sanjeewa
 */
public class SecondPage extends javax.swing.JFrame {

    /**
     * Creates new form SecondPage
     */
    public SecondPage() {
        try {
            initComponents();
        } catch (Exception e) {
            // If NetBeans form initialization fails, create a simple fallback UI
            System.err.println("Form initialization failed, creating fallback UI: " + e.getMessage());
            initSimpleComponents();
        }
        setupRoleBasedAccess();
    }
    
    /**
     * Fallback UI initialization when NetBeans form fails
     */
    private void initSimpleComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setSize(600, 400);
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        
        // Create basic label
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36));
        jLabel1.setText("Library Management System");
        jLabel1.setBounds(50, 20, 500, 50);
        getContentPane().add(jLabel1);
    }
    
    /**
     * Setup UI based on current user's role
     */
    private void setupRoleBasedAccess() {
        UserDAO.User currentUser = SessionManager.getCurrentUser();
        
        if (currentUser == null) {
            // If no user logged in, redirect to login
            JOptionPane.showMessageDialog(this, 
                "Please log in to continue!", 
                "Authentication Required", 
                JOptionPane.WARNING_MESSAGE);
            FirstPage fp = new FirstPage();
            fp.setVisible(true);
            dispose();
            return;
        }
        
        // Set title based on role
        switch (currentUser.getUserRole()) {
            case ADMIN:
                setTitle("Library Management System - Admin Panel");
                // Admin has access to everything
                addAdminButtons();
                break;
            case LIBRARIAN:
                setTitle("Library Management System - Librarian Panel");
                // Librarian has access to books and members, but not librarian management
                addLibrarianButtons();
                break;
            case MEMBER:
                setTitle("Library Management System - Member Panel");
                // Members shouldn't reach this page, redirect to HomePage
                JOptionPane.showMessageDialog(this, 
                    "Members don't have access to this section!", 
                    "Access Denied", 
                    JOptionPane.WARNING_MESSAGE);
                HomePage hp = new HomePage();
                hp.setVisible(true);
                dispose();
                return;
        }
        
        // Add role indicator
        System.out.println("Logged in as: " + currentUser.getName() + " (" + currentUser.getUserRole() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null); // Use null layout instead of AbsoluteLayout

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setText("Borrow Book");
        jButton1.setBounds(150, 70, 250, 50);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton2.setText("Return Book");
        jButton2.setBounds(150, 180, 251, 50);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Images/New Background.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 540, 400);
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Borrow Book button - navigate to BorrowingManagement
        BorrowingManagement bm = new BorrowingManagement();
        bm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Return Book button action - navigate to User Details
        User_Details ud = new User_Details();
        ud.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Add additional navigation buttons for Admin users
     */
    private void addAdminButtons() {
        // Set a better window size for admin view
        setSize(900, 650);
        setLocationRelativeTo(null);
        
        // Create a welcome message
        JLabel welcomeLabel = new JLabel("Administrator Dashboard");
        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 32));
        welcomeLabel.setBounds(280, 30, 400, 50);
        getContentPane().add(welcomeLabel);
        
        // Create section for book management
        JLabel bookSectionLabel = new JLabel("Book Management");
        bookSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20));
        bookSectionLabel.setBounds(100, 120, 200, 30);
        getContentPane().add(bookSectionLabel);
        
        // Add Book Details button
        JButton bookDetailsBtn = new JButton("Manage Books");
        bookDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18));
        bookDetailsBtn.setBounds(100, 160, 200, 60);
        bookDetailsBtn.addActionListener(e -> {
            Book_Details bd = new Book_Details();
            bd.setVisible(true);
            dispose();
        });
        getContentPane().add(bookDetailsBtn);
        
        // Create section for user management
        JLabel userSectionLabel = new JLabel("User Management");
        userSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20));
        userSectionLabel.setBounds(350, 120, 200, 30);
        getContentPane().add(userSectionLabel);
        
        // Add User Details button
        JButton userDetailsBtn = new JButton("Manage Users");
        userDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18));
        userDetailsBtn.setBounds(350, 160, 200, 60);
        userDetailsBtn.addActionListener(e -> {
            User_Details ud = new User_Details();
            ud.setVisible(true);
            dispose();
        });
        getContentPane().add(userDetailsBtn);
        
        // Create section for system administration
        JLabel adminSectionLabel = new JLabel("System Administration");
        adminSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20));
        adminSectionLabel.setBounds(600, 120, 250, 30);
        getContentPane().add(adminSectionLabel);
        
        // Add Admin Panel button
        JButton adminPanelBtn = new JButton("Admin Panel");
        adminPanelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18));
        adminPanelBtn.setBounds(600, 160, 200, 60);
        adminPanelBtn.addActionListener(e -> {
            AdminPanel ap = new AdminPanel();
            ap.setVisible(true);
            dispose();
        });
        getContentPane().add(adminPanelBtn);
        
        // Create section for borrowing management
        JLabel borrowSectionLabel = new JLabel("Borrowing Management");
        borrowSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20));
        borrowSectionLabel.setBounds(225, 250, 250, 30);
        getContentPane().add(borrowSectionLabel);
        
        // Add Borrowing Management button
        JButton borrowingBtn = new JButton("Manage Borrowing");
        borrowingBtn.setFont(new java.awt.Font("Segoe UI", 1, 18));
        borrowingBtn.setBounds(225, 290, 200, 60);
        borrowingBtn.addActionListener(e -> {
            BorrowingManagement bm = new BorrowingManagement();
            bm.setVisible(true);
            dispose();
        });
        getContentPane().add(borrowingBtn);
        
        // Add System Reports button
        JButton reportsBtn = new JButton("System Reports");
        reportsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18));
        reportsBtn.setBounds(475, 290, 200, 60);
        reportsBtn.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, 
                "System Reports feature coming soon!", 
                "Reports", 
                JOptionPane.INFORMATION_MESSAGE);
        });
        getContentPane().add(reportsBtn);
        
        // Add logout button in a better position
        JButton logoutBtn = new JButton("Logout");
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 16));
        logoutBtn.setBounds(750, 20, 100, 40);
        logoutBtn.addActionListener(e -> {
            SessionManager.logout();
            JOptionPane.showMessageDialog(this, "Logged out successfully!");
            FirstPage fp = new FirstPage();
            fp.setVisible(true);
            dispose();
        });
        getContentPane().add(logoutBtn);
        
        // Add a footer with user info
        UserDAO.User currentUser = SessionManager.getCurrentUser();
        if (currentUser != null) {
            JLabel userInfoLabel = new JLabel("Logged in as: " + currentUser.getName() + " (Administrator)");
            userInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
            userInfoLabel.setBounds(50, 570, 400, 20);
            getContentPane().add(userInfoLabel);
        }
        
        // Refresh the layout
        revalidate();
        repaint();
    }

    /**
     * Add navigation buttons for Librarian users
     */
    private void addLibrarianButtons() {
        // Set optimal window size for librarian view
        setSize(900, 700);
        setLocationRelativeTo(null);
        
        // Set background color for better appearance
        getContentPane().setBackground(new java.awt.Color(245, 245, 245));
        
        // Create header section
        JLabel headerLabel = new JLabel("Library Management System");
        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 28));
        headerLabel.setForeground(new java.awt.Color(41, 128, 185));
        headerLabel.setBounds(280, 20, 400, 40);
        getContentPane().add(headerLabel);
        
        JLabel subtitleLabel = new JLabel("Librarian Dashboard");
        subtitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 16));
        subtitleLabel.setForeground(new java.awt.Color(127, 140, 141));
        subtitleLabel.setBounds(380, 60, 200, 25);
        getContentPane().add(subtitleLabel);
        
        // Create main content area with organized sections
        
        // Section 1: Book Management (Left Column)
        JLabel bookSectionLabel = new JLabel("📚 Book Management");
        bookSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        bookSectionLabel.setForeground(new java.awt.Color(46, 204, 113));
        bookSectionLabel.setBounds(80, 130, 250, 30);
        getContentPane().add(bookSectionLabel);
        
        JButton bookDetailsBtn = new JButton("<html><center>Manage Books<br><small>Add, Edit, Remove Books</small></center></html>");
        bookDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14));
        bookDetailsBtn.setBackground(new java.awt.Color(46, 204, 113));
        bookDetailsBtn.setForeground(java.awt.Color.WHITE);
        bookDetailsBtn.setBounds(80, 170, 250, 80);
        bookDetailsBtn.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        bookDetailsBtn.addActionListener(e -> {
            Book_Details bd = new Book_Details();
            bd.setVisible(true);
            dispose();
        });
        getContentPane().add(bookDetailsBtn);
        
        // Section 2: User Management (Right Column)
        JLabel userSectionLabel = new JLabel("👥 User Management");
        userSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        userSectionLabel.setForeground(new java.awt.Color(52, 152, 219));
        userSectionLabel.setBounds(450, 130, 250, 30);
        getContentPane().add(userSectionLabel);
        
        JButton userDetailsBtn = new JButton("<html><center>Manage Users<br><small>View, Edit User Details</small></center></html>");
        userDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14));
        userDetailsBtn.setBackground(new java.awt.Color(52, 152, 219));
        userDetailsBtn.setForeground(java.awt.Color.WHITE);
        userDetailsBtn.setBounds(450, 170, 250, 80);
        userDetailsBtn.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        userDetailsBtn.addActionListener(e -> {
            User_Details ud = new User_Details();
            ud.setVisible(true);
            dispose();
        });
        getContentPane().add(userDetailsBtn);
        
        // Section 3: Borrowing Management (Center, Second Row)
        JLabel borrowSectionLabel = new JLabel("📖 Borrowing Management");
        borrowSectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        borrowSectionLabel.setForeground(new java.awt.Color(230, 126, 34));
        borrowSectionLabel.setBounds(265, 290, 300, 30);
        getContentPane().add(borrowSectionLabel);
        
        JButton borrowingBtn = new JButton("<html><center>Manage Borrowing<br><small>Issue & Return Books</small></center></html>");
        borrowingBtn.setFont(new java.awt.Font("Segoe UI", 1, 14));
        borrowingBtn.setBackground(new java.awt.Color(230, 126, 34));
        borrowingBtn.setForeground(java.awt.Color.WHITE);
        borrowingBtn.setBounds(265, 330, 250, 80);
        borrowingBtn.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        borrowingBtn.addActionListener(e -> {
            BorrowingManagement bm = new BorrowingManagement();
            bm.setVisible(true);
            dispose();
        });
        getContentPane().add(borrowingBtn);
        
        // Quick Action Buttons (Third Row)
        JLabel quickActionsLabel = new JLabel("⚡ Quick Actions");
        quickActionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16));
        quickActionsLabel.setForeground(new java.awt.Color(155, 89, 182));
        quickActionsLabel.setBounds(80, 450, 200, 25);
        getContentPane().add(quickActionsLabel);
        
        JButton quickBorrowBtn = new JButton("Quick Borrow");
        quickBorrowBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        quickBorrowBtn.setBackground(new java.awt.Color(155, 89, 182));
        quickBorrowBtn.setForeground(java.awt.Color.WHITE);
        quickBorrowBtn.setBounds(80, 480, 140, 40);
        quickBorrowBtn.addActionListener(e -> {
            // Navigate to borrowing with quick mode
            BorrowingManagement bm = new BorrowingManagement();
            bm.setVisible(true);
            dispose();
        });
        getContentPane().add(quickBorrowBtn);
        
        JButton quickReturnBtn = new JButton("Quick Return");
        quickReturnBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        quickReturnBtn.setBackground(new java.awt.Color(155, 89, 182));
        quickReturnBtn.setForeground(java.awt.Color.WHITE);
        quickReturnBtn.setBounds(240, 480, 140, 40);
        quickReturnBtn.addActionListener(e -> {
            // Navigate to borrowing with return mode
            BorrowingManagement bm = new BorrowingManagement();
            bm.setVisible(true);
            dispose();
        });
        getContentPane().add(quickReturnBtn);
        
        JButton searchBtn = new JButton("Search Books");
        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        searchBtn.setBackground(new java.awt.Color(155, 89, 182));
        searchBtn.setForeground(java.awt.Color.WHITE);
        searchBtn.setBounds(400, 480, 140, 40);
        searchBtn.addActionListener(e -> {
            Book_Details bd = new Book_Details();
            bd.setVisible(true);
            dispose();
        });
        getContentPane().add(searchBtn);
        
        JButton viewReportsBtn = new JButton("View Reports");
        viewReportsBtn.setFont(new java.awt.Font("Segoe UI", 0, 12));
        viewReportsBtn.setBackground(new java.awt.Color(155, 89, 182));
        viewReportsBtn.setForeground(java.awt.Color.WHITE);
        viewReportsBtn.setBounds(560, 480, 140, 40);
        viewReportsBtn.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, 
                "Reports feature coming soon!", 
                "Reports", 
                JOptionPane.INFORMATION_MESSAGE);
        });
        getContentPane().add(viewReportsBtn);
        
        // Footer section
        UserDAO.User currentUser = SessionManager.getCurrentUser();
        if (currentUser != null) {
            JLabel userInfoLabel = new JLabel("👤 Logged in as: " + currentUser.getName() + " (Librarian)");
            userInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
            userInfoLabel.setForeground(new java.awt.Color(127, 140, 141));
            userInfoLabel.setBounds(50, 580, 400, 20);
            getContentPane().add(userInfoLabel);
            
            // Add current date/time
            JLabel dateLabel = new JLabel("📅 " + java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("MMM dd, yyyy - HH:mm")));
            dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 12));
            dateLabel.setForeground(new java.awt.Color(127, 140, 141));
            dateLabel.setBounds(50, 600, 300, 20);
            getContentPane().add(dateLabel);
        }
        
        // Logout button - positioned prominently
        JButton logoutBtn = new JButton("🚪 Logout");
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14));
        logoutBtn.setBackground(new java.awt.Color(231, 76, 60));
        logoutBtn.setForeground(java.awt.Color.WHITE);
        logoutBtn.setBounds(750, 20, 120, 45);
        logoutBtn.setBorder(javax.swing.BorderFactory.createRaisedBevelBorder());
        logoutBtn.addActionListener(e -> {
            int choice = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to logout?", 
                "Confirm Logout", 
                JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                SessionManager.logout();
                JOptionPane.showMessageDialog(this, "Logged out successfully!");
                FirstPage fp = new FirstPage();
                fp.setVisible(true);
                dispose();
            }
        });
        getContentPane().add(logoutBtn);
        
        // Refresh the layout
        revalidate();
        repaint();
    }
}
